// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class WishHappyNewYearBindings
    {
        readonly ICloudCodeService k_Service;
        public WishHappyNewYearBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SendPlayerMessage(string playerId, string playerName, string leaderboardId, double score)
        {
            await k_Service.CallModuleEndpointAsync(
                "WishHappyNewYear",
                "SendPlayerMessage",
                new Dictionary<string, object>()
                {
                    {"playerId", playerId},
                    {"playerName", playerName},
                    {"leaderboardId", leaderboardId},
                    {"score", score},
                });
        }
    }
}
