// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class WishHappyNewYearBindings
    {
        readonly ICloudCodeService k_Service;
        public WishHappyNewYearBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SendProjectMessage(string message, string messageType)
        {
            await k_Service.CallModuleEndpointAsync(
                "WishHappyNewYear",
                "SendProjectMessage",
                new Dictionary<string, object>()
                {
                    {"message", message},
                    {"messageType", messageType},
                });
        }
    }
}
